cookie:
  expiry_days: 1
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    admin:
      email: admin@example.com
      failed_login_attempts: 0
      logged_in: false
      name: Admin User
      password: $2b$12$c4EDKIZDlEnuh4PZewQY/e1BHrucgM2DGc14LqZog2kcVClMJx1k6
    ryan:
      email: Muhammadryan.giggs@gmail.com
      logged_in: false
      name: ryan
      password: $2b$12$xCjdTKwX3QjaLGOx3t.jX.Gq5doK4v3VR9WvAzrm/4F6zGwmE/mdO
    user:
      email: user@example.com
      failed_login_attempts: 0
      logged_in: false
      name: Regular User
      password: $2b$12$UHUO7cZvVFJVr2NcxApRyefmHEPrw/imUrY6DTkKxSMJDXvAfphEu
pre-authorized:
  emails: []
